### ISSUE TITLE
GetPublicKeyStatus function modification proposal

### ISSUE THREAD

**Issue by MisiakGeo** [alastria/temp-alastriaID-truffle-contracts#58]
Hello all, 
In AlastriaPublicKeyRegistry.sol (located [here](https://github.com/alastria/alastriaID-truffle-contracts/blob/master/contracts/registry/AlastriaPublicKeyRegistry.sol)), I have a question regarding the line 88 ([here](https://github.com/alastria/alastriaID-truffle-contracts/blob/master/contracts/registry/AlastriaPublicKeyRegistry.sol#L88)), the function **getPublicKeyStatus** accepts type bytes32 data of publicKey and makes the assumption that you already know the keccak256 of the input. As in every position within the contract the publicKey is passed as string and the keccak256 is computed within the function, wouldn't it more appropriate if we transform it accordingly, as presented in the code block below or there is a reason behind that?

```
function getPublicKeyStatus(address subject, string memory publicKey) view public validAddress(subject) returns (bool exists, uint status, uint startDate, uint endDate)
 PublicKey storage value = publicKeyRegistry[subject][getKeyHash(publicKey)];
 return (value.exists, value.status, value.startDate, value.endDate);
}
```

Thank you.

**Comment by rober12** [comment]
Hello George,

In the 2.2.0 version being worked on, all functions and data structures of AlastriaPublicKeyRegistry.sol will be reimplemented to work with the hashes (keccak256) of the public keys instead of the public key in clear (bytes32), for obvious reasons.
So the change you propose will be made in this next version coming soon.

Thank you very much for your contribution.

**Comment by MisiakGeo** [comment]
Thank you very much.

**Comment by MisiakGeo** [comment]
Closing this issue, due to the fact that it is going to be rectified in the upcoming version 2.2.0.
